In [2]:
import pandas as pd
df = pd.read_csv('data/sleep_health_lifestyle_dataset.csv')

df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration (hours),Quality of Sleep (scale: 1-10),Physical Activity Level (minutes/day),Stress Level (scale: 1-10),BMI Category,Blood Pressure (systolic/diastolic),Heart Rate (bpm),Daily Steps,Sleep Disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 13 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Person ID                              400 non-null    int64
 1   Gender                                 400 non-null    object
 2   Age                                    400 non-null    int64
 3   Occupation                             400 non-null    object
 4   Sleep Duration (hours)                 400 non-null    float64
 5   Quality of Sleep (scale: 1-10)         400 non-null    float64
 6   Physical Activity Level (minutes/day)  400 non-null    int64
 7   Stress Level (scale: 1-10)             400 non-null    int64
 8   BMI Category                           400 non-null    object
 9   Blood Pressure (systolic/diastolic)    400 non-null    object
 10  Heart Rate (bpm)                       400 non-null    int64
 11  Daily Steps                            400 non-null    int64
 12  Sleep Disorder                         110 non-null    object
dtypes: float64(2), int64(6), object(5)
memory usage: 40.8+ KB

In [4]:
df.fillna("None", inplace = True)